# TODO: Use dataset_name to determine paths of other fields
dataset_path: /media/donceykong/donceys_data_ssd/datasets/CU_MULTI/data # path to dataset
dataset_name: CU-MULTI  # "KITTI-360" or "CU-MULTI"
infer_or_train: infer   # "train" or "infer"
# data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/OSM-AS-A-PRIOR-FULL/CENet/ce_net/config/data_cfg_cu_multi.yaml
data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/OSM-AS-A-PRIOR-FULL/CENet/ce_net/config/labels/semantic-kitti.yaml
# environments: ["main_campus"]
# robots: ["robot1", "robot2", "robot3", "robot4"]

inference:
  # For regular Semantic-KITTI labels
  model_path: /media/donceykong/donceys_data_ssd/models/CENet/semantic_kitti/1024_valid5
  # For KITTI-360 OSM-Semantic labels
  split: test # "valid", "train", or "test"